apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
        - name: python-flask-app
          image: YOUR_FLASK_APP_IMAGE # Replace with your Docker image path
          ports:
            - containerPort: 5000
        - name: secretless-broker
          image: cyberark/secretless-broker:latest
          args: ["-f", "/etc/secretless/secretless.yml"]
          volumeMounts:
            - name: secretless-config
              mountPath: /etc/secretless
      volumes:
        - name: secretless-config
          configMap:
            name: secretless-config
